-- ===================================================================
--  SPACE SHIELD 패키지 발주·재고 관리대장 — Supabase 스키마
--  Supabase 대시보드 ▸ SQL Editor 에 통째로 붙여넣고 RUN (한 번만)
--  · 읽기: 누구나 (모두에게 같은 화면)
--  · 쓰기: 로그인한 사람만 (RLS)  ← publishable(anon) 키가 공개돼도 안전
-- ===================================================================

-- 1) 품목 테이블 ----------------------------------------------------
create table if not exists public.pkg_items (
  id              bigint generated by default as identity primary key,
  code            text not null,              -- 관리코드 (G-BOX-02)
  name_ko         text not null,              -- 한국명
  alias           text default '',            -- 별칭 (물류팀 은어, 예: 반달)
  type            text default '기타',         -- 비닐 / 박스·지류 / 스티커 / 기타
  cat             text default '',            -- 카테고리 (NAS 분류: G BOX / C OPP / Armor Flex)
  name_en         text default '',            -- 영문명 (작업지시서 기준)
  name_cn         text default '',            -- 중문명 (거래처 소통용)
  spec            text default '',            -- 규격 / 사양
  price           numeric default 0,          -- 단가 (¥)
  moq             int    default 0,
  lead            int    default 14,          -- 리드타임(일)
  safety          int    default 0,           -- 안전재고
  box_china       int    default 0,           -- 중국창고 박스 수 (수동, 러프)
  box_forwarder   int    default 0,           -- 포워딩 박스 수
  box_korea       int    default 0,           -- 국내 박스 수
  stock_china     int    default 0,           -- 중국창고 재고
  stock_forwarder int    default 0,           -- 포워딩 재고
  stock_korea     int    default 0,           -- 국내 재고
  memo            text default '',
  nas_path        text default '',            -- NAS 전체 서버 경로 (텍스트 복사용)
  flow_url        text default '',            -- FLOW 기획서 링크 URL
  buy_url         text default '',            -- 구매링크 URL (재주문/구매 페이지)
  status          text default '',            -- 수동 상태 뱃지 ('' 자동 / 시안 / 단종)
  photo           text default '',            -- 대표 사진 URL (= photos[0], 하위호환)
  photos          jsonb default '[]',         -- 사진 여러 장 URL 배열
  links           jsonb default '[]',         -- 연관 카드(품목 id 배열, 양방향 표시)
  sheet           text default '',            -- 작업지시서 이미지 URL (Storage)
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- 2) 주문 테이블 ----------------------------------------------------
create table if not exists public.pkg_orders (
  id           bigint generated by default as identity primary key,
  item_id      bigint references public.pkg_items(id) on delete cascade,
  stage        text default 'request',        -- request/ordered/chinaWh/forwarder/arrived
  qty          int    default 0,
  price        numeric default 0,
  requested_by text default '',               -- 요청자 (앱의 by)
  memo         text default '',
  order_date   text default '',               -- 발주일 (YYYY-MM-DD)
  eta          text default '',               -- 예상납기
  created      text default '',               -- 요청 등록일
  created_at   timestamptz default now()
);

create index if not exists idx_pkg_orders_item on public.pkg_orders(item_id);

-- 수정 시 updated_at 자동 갱신
create or replace function public.pkg_touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists trg_pkg_items_touch on public.pkg_items;
create trigger trg_pkg_items_touch before update on public.pkg_items
  for each row execute function public.pkg_touch_updated_at();

-- 3) RLS: 누구나 읽기, 로그인한 사람만 추가/수정/삭제 ----------------
alter table public.pkg_items  enable row level security;
alter table public.pkg_orders enable row level security;

drop policy if exists "pkg_items public read"  on public.pkg_items;
drop policy if exists "pkg_items auth write"    on public.pkg_items;
create policy "pkg_items public read" on public.pkg_items for select using (true);
create policy "pkg_items auth write"  on public.pkg_items for all to authenticated using (true) with check (true);

drop policy if exists "pkg_orders public read" on public.pkg_orders;
drop policy if exists "pkg_orders auth write"   on public.pkg_orders;
create policy "pkg_orders public read" on public.pkg_orders for select using (true);
create policy "pkg_orders auth write"  on public.pkg_orders for all to authenticated using (true) with check (true);

-- 4) 이미지 Storage 버킷 (공개 읽기, 로그인 쓰기) -------------------
insert into storage.buckets (id, name, public)
values ('pkg-images', 'pkg-images', true)
on conflict (id) do nothing;

drop policy if exists "pkg img public read" on storage.objects;
drop policy if exists "pkg img auth write"   on storage.objects;
create policy "pkg img public read" on storage.objects
  for select using (bucket_id = 'pkg-images');
create policy "pkg img auth write" on storage.objects
  for all to authenticated
  using (bucket_id = 'pkg-images') with check (bucket_id = 'pkg-images');

-- 4-1) 실시간 동기화 publication (다른 사용자의 변경 자동 반영) --------
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='pkg_items') then
    alter publication supabase_realtime add table public.pkg_items;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='pkg_orders') then
    alter publication supabase_realtime add table public.pkg_orders;
  end if;
end $$;

-- 5) 예시 데이터 (원하면 이 블록만 지우고 RUN) ----------------------
insert into public.pkg_items
  (id, code, name_ko, alias, type, cat, name_en, name_cn, spec, price, moq, lead, safety, stock_china, stock_forwarder, stock_korea, memo)
values
  (1,'G-OPP-04','OPP 지퍼백 (로고 인쇄)','','비닐','G OPP','SPACE SHIELD_G OPP_No-04 (V2)','OPP袋 180×230mm 前透明后白色印刷','180×230mm · 전면 투명 / 후면 백색 인쇄 · 타공 2mm',0.35,30000,15,20000,0,12000,6500,'품파이 포장 (品派包装) · 주문서 No.007001'),
  (2,'G-BOX-02','범용 박스 2호 (V2)','반달','박스·지류','G BOX','G BOX No.2 (V2)','通用纸盒 2号','예시 — 규격 입력 필요',0.6,20000,18,15000,25000,0,9000,'예시 데이터 — 실제 값으로 수정하세요'),
  (3,'C-OPP-WS-S','워치 스트랩 OPP S size (V4)','','비닐','C OPP','Watch Strap OPP S (V4)','表带OPP袋 S号 (V4)','예시 — 규격 입력 필요',0.12,50000,12,30000,0,0,22000,'예시 데이터'),
  (4,'AF-STK-GU','가드업 라인업 사이드 스티커','','스티커','Armor Flex','GuardUp Lineup Side Sticker','GuardUp 侧面贴纸','예시 — 규격 입력 필요',0.05,100000,10,50000,0,0,120000,'예시 데이터'),
  (5,'G-STK-DUST','먼지 제거 스티커 세트','먼지스티커','스티커','G STK','Dust Removal Sticker Set','除尘贴纸套装（清洁屏幕用）','로고 스티커 2매 + 먼지 제거 스티커 1매 세트 · 흑색 인쇄',0.09,50000,10,40000,30000,0,18000,'액정보호필름 동봉용 · 예시 수치')
on conflict (id) do nothing;

insert into public.pkg_orders
  (id, item_id, stage, qty, price, requested_by, memo, order_date, eta, created)
values
  (101,1,'ordered',30000,0.35,'김정환','주문서 No.007001','2026-07-09','2026-07-24','2026-07-09'),
  (100,1,'arrived',30000,0.32,'김정환','','2025-11-14','2025-11-29','2025-11-14'),
  (102,2,'request',20000,0.6,'물류팀 조아름','반달 얼마 안 남았습니다!','','','2026-07-10'),
  (103,2,'arrived',20000,0.58,'김정환','','2026-04-02','2026-04-20','2026-04-02'),
  (104,5,'arrived',50000,0.08,'김정환','','2025-08-21','2025-08-31','2025-08-21'),
  (105,5,'arrived',50000,0.09,'김정환','단가 인상 (원자재)','2026-03-12','2026-03-22','2026-03-12')
on conflict (id) do nothing;

-- identity 시퀀스를 예시 최대 id 뒤로 이동 (다음 자동 id 충돌 방지)
select setval(pg_get_serial_sequence('public.pkg_items','id'),  (select max(id) from public.pkg_items));
select setval(pg_get_serial_sequence('public.pkg_orders','id'), (select max(id) from public.pkg_orders));

-- 끝. 이제 SETUP.md 6단계(로그인 계정 만들기)로.
